build: backport fixes to make-dist
Signed-off-by: Milind Changire <mchangir@redhat.com>

diff --git a/make-dist b/make-dist
--- a/make-dist
+++ b/make-dist
@@ -23,7 +23,7 @@ version=$1
 [ -z "$version" ] && version=$(git describe --long --match 'v*' | sed 's/^v//')
 if expr index $version '-' > /dev/null; then
     rpm_version=$(echo $version | cut -d - -f 1-1)
-    rpm_release=$(echo $version | cut -d - -f 2- | sed 's/-/./')
+    rpm_release=$(echo $version | cut -d - -f 2- | sed 's/-/./g')
 else
     rpm_version=$version
     rpm_release=0
@@ -35,7 +35,8 @@ echo "version $version"
 # update submodules
 echo "updating submodules..."
 force=$(if git submodule usage 2>&1 | grep --quiet 'update.*--force'; then echo --force ; fi)
-if ! git submodule sync || ! git submodule update $force --init --recursive; then
+quiet_or_progress=$(if test -n "$JENKINS_URL"; then echo --quiet; else echo --progress; fi)
+if ! git submodule sync || ! git submodule update $force --init --recursive $quiet_or_progress; then
     echo "Error: could not initialize submodule projects"
     echo "  Network connectivity might be required."
     exit 1
@@ -51,11 +52,11 @@ download_from() {
         url_base=$1
         shift
         if [ -z $url_base ]; then
-            echo "Error: failed to download $name."
+            echo "Error: failed to download $fname."
             exit
         fi
         url=$url_base/$fname
-        wget -c --no-verbose -O $fname $url
+        wget --no-verbose -O $fname $url
         if [ $? != 0 -o ! -e $fname ]; then
             echo "Download of $url failed"
         elif [ $(sha256sum $fname | awk '{print $1}') != $sha256 ]; then
@@ -138,9 +139,9 @@ build_dashboard_frontend() {
   . $TEMP_DIR/bin/activate
   NG_CLI_ANALYTICS=false timeout 1h npm ci
   echo "Building ceph-dashboard frontend with build:localize script";
-  # we need to use "--" because so that "--prod" survives accross all
-  # scripts redirections inside package.json
-  npm run build:localize -- --prod
+  # we need to use "--" because so that "--configuration production"
+  # survives accross all scripts redirections inside package.json
+  DASHBOARD_FRONTEND_LANGS="ALL" npm run build:localize -- --configuration production
   deactivate
   cd $CURR_DIR
   rm -rf $TEMP_DIR
@@ -154,7 +155,7 @@ generate_rook_ceph_client() {
 
 # clean out old cruft...
 echo "cleanup..."
-rm -f $outfile*
+rm -rf $outfile*
 
 # build new tarball
 echo "building tarball..."
@@ -168,6 +169,19 @@ echo "including src/.git_version, ceph.spec"
 
 (git rev-parse HEAD ; echo $version) 2> /dev/null > src/.git_version
 
+if [ -r /etc/os-release ]; then
+    source /etc/os-release
+    case $ID in
+        opensuse*|suse|sles)
+            if [ "x$rpm_release" != "x0" ] ; then
+                rpm_release=$(echo $rpm_release | sed 's/.g/+g/')
+                rpm_version="${rpm_version}.${rpm_release}"
+                rpm_release="0"
+            fi
+            ;;
+    esac
+fi
+
 for spec in ceph.spec.in; do
     cat $spec |
         sed "s/@PROJECT_VERSION@/$rpm_version/g" |
@@ -180,9 +194,8 @@ tar cvf $outfile.version.tar $outfile/src/.git_version $outfile/ceph.spec
 # at the three URLs referenced below (may involve uploading to download.ceph.com)
 boost_version=1.75.0
 download_boost $boost_version 953db31e016db7bb207f11432bef7df100516eeb746843fa0486a222e3fd49cb \
-               https://boostorg.jfrog.io/artifactory/main/release/$boost_version/source \
-               https://downloads.sourceforge.net/project/boost/boost/$boost_version \
-               https://download.ceph.com/qa
+               https://download.ceph.com/qa \
+               https://archives.boost.io/release/$boost_version/source
 download_liburing 0.7 8e2842cfe947f3a443af301bdd6d034455536c38a455c7a700d0c1ad165a7543 \
                   https://github.com/axboe/liburing/archive \
                   https://git.kernel.dk/cgit/liburing/snapshot
